main: fr.snipertvmc.essentialsxgui.Main


name: EssentialsX-GUI
description: GUI Addon for EssentialsX
website: https://github.com/SniperTVmc/EssentialsX-GUI/
author: Sniper_TVmc


version: ${version}
api-version: 1.13


depend:
  - Essentials
softdepend:
  - PlaceholderAPI


commands:

  essentialsxgui:
    description: Main command for management of the plugin.
    aliases: [exg, egui, essentialsgui]


permissions:

  essentialsxgui.admin.update:
    description: Allows to receive update notifications when a new version of the plugin is available.
    default: op

  essentialsxgui.command.essentialsxgui:
    description: Allows to use the /essentialsxgui command.
    default: op

  essentialsxgui.command.essentialsxgui.reload:
    description: Allows to use the /essentialsxgui reload command.
    default: op

  essentialsxgui.command.essentialsxgui.debug:
    description: Allows to use the /essentialsxgui debug command.
    default: op

  essentialsxgui.kits.admin:
    description: Allows to manage kits through the GUI.
    default: op

  essentialsxgui.warps.admin:
    description: Allows to manage warps through the GUI.
    default: op